before_build:
- dotnet restore src\MyCoreWebApp\project.json
build:
  project: MyCoreWebApp.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: dotnet publish src\MyCoreWebApp -o publish -c Debug