before_build:
- dotnet restore src\MyCoreWebApp\project.json
build:
  project: MyCoreWebApp.sln
  parallel: true
  verbosity: minimal
after_build:
- dotnet publish .\src\MyCoreWebApp --output %appveyor_build_folder%\dist --configuration Debug --no-build
- dir dist