image: Visual Studio 2015 - GCE
environment:
  website_name: my-aspnetcore-rc2
  website_psw:
    secure: zTHSWn+iE4RfNYHExaZxBEEoOrcu40MUtZKOV704vHlRuBCHfNa7iE0G9l6nriCprhHEuUddb733Qgpb56V6Tw==
before_build:
- dotnet restore src\MyCoreWebApp\project.json
build:
  project: MyCoreWebApp.sln
  parallel: true
  verbosity: minimal
after_build:
- dotnet publish .\src\MyCoreWebApp --output %appveyor_build_folder%\dist --configuration Debug --no-build
test: off
artifacts:
- path: dist
  name: web-app
deploy_script:
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp=''%appveyor_build_folder%\dist'' -dest:IisApp=''%website_name%'',ComputerName=''https://%website_name%.scm.azurewebsites.net/msdeploy.axd'',UserName=''$%website_name%'',Password=''%website_psw%'',IncludeAcls=''False'',AuthType=''Basic'' -verb:sync -enablerule:AppOffline -enableRule:DoNotDeleteRule -retryAttempts:2'
